-- My Fitness Buddy — expand the seeded exercise catalog to an exhaustive list
-- per muscle group. Idempotent: relies on the partial unique index
-- exercises_seed_unique (body_part, name) where user_id is null, created in
-- 0001. Apply via the Supabase SQL editor or `supabase db push`.

insert into public.exercises (body_part, name, user_id, is_custom) values
  -- Chest
  ('chest', 'Barbell Bench Press', null, false),
  ('chest', 'Incline Barbell Bench Press', null, false),
  ('chest', 'Decline Barbell Bench Press', null, false),
  ('chest', 'Dumbbell Bench Press', null, false),
  ('chest', 'Incline Dumbbell Press', null, false),
  ('chest', 'Decline Dumbbell Press', null, false),
  ('chest', 'Machine Chest Press', null, false),
  ('chest', 'Smith Machine Bench Press', null, false),
  ('chest', 'Chest Fly', null, false),
  ('chest', 'Incline Dumbbell Fly', null, false),
  ('chest', 'Cable Crossover', null, false),
  ('chest', 'Pec Deck', null, false),
  ('chest', 'Push-up', null, false),
  ('chest', 'Dips (Chest)', null, false),
  -- Back
  ('back', 'Deadlift', null, false),
  ('back', 'Conventional Deadlift', null, false),
  ('back', 'Sumo Deadlift', null, false),
  ('back', 'Pull-up', null, false),
  ('back', 'Chin-up', null, false),
  ('back', 'Lat Pulldown', null, false),
  ('back', 'Close-grip Lat Pulldown', null, false),
  ('back', 'Bent-over Row', null, false),
  ('back', 'Barbell Row', null, false),
  ('back', 'Pendlay Row', null, false),
  ('back', 'Dumbbell Row', null, false),
  ('back', 'Seated Cable Row', null, false),
  ('back', 'T-Bar Row', null, false),
  ('back', 'Machine Row', null, false),
  ('back', 'Straight-arm Pulldown', null, false),
  ('back', 'Face Pull', null, false),
  ('back', 'Hyperextension', null, false),
  ('back', 'Rack Pull', null, false),
  -- Biceps
  ('biceps', 'Barbell Curl', null, false),
  ('biceps', 'EZ-bar Curl', null, false),
  ('biceps', 'Dumbbell Curl', null, false),
  ('biceps', 'Incline Dumbbell Curl', null, false),
  ('biceps', 'Hammer Curl', null, false),
  ('biceps', 'Concentration Curl', null, false),
  ('biceps', 'Preacher Curl', null, false),
  ('biceps', 'Cable Curl', null, false),
  ('biceps', 'Spider Curl', null, false),
  -- Triceps
  ('triceps', 'Tricep Pushdown', null, false),
  ('triceps', 'Rope Pushdown', null, false),
  ('triceps', 'Overhead Tricep Extension', null, false),
  ('triceps', 'Skull Crusher', null, false),
  ('triceps', 'Close-grip Bench Press', null, false),
  ('triceps', 'Dips (Triceps)', null, false),
  ('triceps', 'Tricep Kickback', null, false),
  ('triceps', 'Dumbbell Overhead Extension', null, false),
  -- Legs
  ('legs', 'Back Squat', null, false),
  ('legs', 'Front Squat', null, false),
  ('legs', 'Goblet Squat', null, false),
  ('legs', 'Hack Squat', null, false),
  ('legs', 'Leg Press', null, false),
  ('legs', 'Romanian Deadlift', null, false),
  ('legs', 'Stiff-leg Deadlift', null, false),
  ('legs', 'Leg Curl', null, false),
  ('legs', 'Seated Leg Curl', null, false),
  ('legs', 'Leg Extension', null, false),
  ('legs', 'Walking Lunge', null, false),
  ('legs', 'Bulgarian Split Squat', null, false),
  ('legs', 'Calf Raise', null, false),
  ('legs', 'Seated Calf Raise', null, false),
  ('legs', 'Hip Thrust', null, false),
  ('legs', 'Glute Bridge', null, false),
  ('legs', 'Step-up', null, false),
  -- Abs
  ('abs', 'Plank', null, false),
  ('abs', 'Side Plank', null, false),
  ('abs', 'Hanging Leg Raise', null, false),
  ('abs', 'Lying Leg Raise', null, false),
  ('abs', 'Cable Crunch', null, false),
  ('abs', 'Crunch', null, false),
  ('abs', 'Sit-up', null, false),
  ('abs', 'Russian Twist', null, false),
  ('abs', 'Bicycle Crunch', null, false),
  ('abs', 'Mountain Climber', null, false),
  ('abs', 'Ab Wheel Rollout', null, false),
  -- Cardio
  ('cardio', 'Treadmill Run', null, false),
  ('cardio', 'Treadmill Walk', null, false),
  ('cardio', 'Outdoor Run', null, false),
  ('cardio', 'Cycling', null, false),
  ('cardio', 'Stationary Bike', null, false),
  ('cardio', 'Rowing Machine', null, false),
  ('cardio', 'Elliptical', null, false),
  ('cardio', 'Stair Climber', null, false),
  ('cardio', 'Jump Rope', null, false),
  ('cardio', 'Swimming', null, false)
on conflict do nothing;
